apiVersion: v1
kind: Secret
metadata:
  name: hrms-secrets
  namespace: hrms
type: Opaque
stringData:
  AUTH_MONGO_URI: mongodb://mongo-auth:27017/hrms_auth
  EMPLOYEE_MONGO_URI: mongodb://mongo-employee:27017/hrms_employee
  LEAVE_MONGO_URI: mongodb://mongo-leave:27017/hrms_leave
  PAYROLL_MONGO_URI: mongodb://mongo-payroll:27017/hrms_payroll
