apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: cloud-native-ops
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://<user>:<password>@<cluster-url>/cloud_native_ops?retryWrites=true&w=majority"
  FRONTEND_ORIGIN: "https://your-domain.com"
